#!/bin/bash

echo ---------------------------------
figlet -f /usr/share/figlet/smslant.flf BUILDING...
echo ---------------------------------
echo Compiling linux executable...
echo ---------------------------------
GOPATH=~/go go build -x -ldflags '-w -s' ./kwe.go
echo ---------------------------------
echo Compiling linux executable...
echo ---------------------------------
GOPATH=~/go GOARCH=arm64 GOOS=android go build -x -ldflags '-w -s' -o ./kwe_android ./kwe.go
echo ---------------------------------
echo Compiling windows executable...
echo ---------------------------------
GOPATH=~/go GOARCH=amd64 GOOS=windows go build -x -ldflags '-w -s' ./kwe.go
echo ---------------------------------
echo Compressing linux executable...
echo ---------------------------------
upx kwe
echo ---------------------------------
echo Compressing android executable...
echo ---------------------------------
upx kwe_android
echo ---------------------------------
echo Compressing windows executable...
echo ---------------------------------
upx kwe.exe
echo ---------------------------------
echo Replacing server executable...
echo ---------------------------------
rm -rf ./kwe2
cp ./kwe ./kwe2
echo Deploying binaries to webdir...
echo ---------------------------------
mv ./kwe.exe ./www/kwe.exe
mv ./kwe ./www/kwe_linux.out
mv ./kwe_android ./www/kwe_android.out
figlet -f /usr/share/figlet/smslant.flf RESTARTING...
echo ---------------------------------
sleep 4
pkill kwe2
